/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'DataTest.DebugPlay+AE722F80F55D5LS' 
 * Target:  'DebugPlay+AE722F80F55D5LS' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
